[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node server.js"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_URL = "${{RAILWAY_BACKEND_URL}}"

[environments.staging.variables] 
NODE_ENV = "staging"
VITE_API_URL = "${{RAILWAY_BACKEND_URL}}"