[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.frontend"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
VITE_API_URL = "${{RAILWAY_BACKEND_URL}}"

[environments.staging.variables] 
NODE_ENV = "staging"
VITE_API_URL = "${{RAILWAY_BACKEND_URL}}"