# Render configuration for TravelPlanner
services:
  # Frontend - React Static Site
  - type: web
    name: travelplanner-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - FastAPI Service  
  - type: web
    name: travelplanner-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: ENVIRONMENT
        value: production

databases:
  - name: travelplanner-db
    databaseName: travelplanner
    user: travelplanner_user