# Render configuration for TravelPlanner
services:
  # Frontend - React Static Site
  - type: web
    name: travelplanner-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - FastAPI Service  
  - type: web
    name: travelplanner-backend
    env: python
    plan: starter
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app.main_simple:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.8