[phases.setup]
nixPkgs = ["...", "python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install poetry==1.6.1",
    "poetry config virtualenvs.create false",
    "poetry install --only=main --no-interaction"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"