[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
PYTHONPATH = "/app"

[environments.staging.variables]
ENVIRONMENT = "staging" 
DEBUG = "true"
PYTHONPATH = "/app"